name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            outfile: nightcode-macos-arm64
          - os: windows-latest
            outfile: nightcode-windows-x64.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install
        working-directory: ./packages/cli

      - run: bun build ./src/index.tsx --compile --outfile ${{ matrix.outfile }}
        working-directory: ./packages/cli

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.outfile }}
          path: ./packages/cli/${{ matrix.outfile }}
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Flatten artifacts
        run: |
          mkdir -p release
          find artifacts -type f -exec mv {} release/ \;
      
      - uses: softprops/action-gh-release@v2
        with:
          files: release/*